### ISSUE TITLE
put the `.erb` file in the `colors/` directory so that everyone can contribute easily 

### ISSUE THREAD

**Issue by krehwell** [arthurealike/vim-J#1]
If I guess it right you use vim-rnb to generate the colorscheme, I think it's better to attach the file with `.erb` too in the dir so that people can contribute by just changing the color hex or even adding different filetypes support in the `.erb` file instead.  
The `.vim` format is so un-readable to edit

**Comment by arthurealike** [comment]
`.erb` file is added.
