### ISSUE TITLE
Transparency for Joker theme.

### ISSUE THREAD

**Issue by z3n-k3rn3l** [arthurealike/vim-J#2]
Joker theme really gives aesthetic pleasure with it's dark colors. But adding an option for transparency would make it better, like  we see in the tokiyo-night vim theme..

**Comment by arthurealike** [comment]
It'll be added soon.

**Comment by arthurealike** [comment]
Transparency is added. Sorry for the delay.

**Comment by z3n-k3rn3l** [comment]
> Transparency is added. Sorry for the delay.

Thanks. Great work
