### ISSUE TITLE
Error when executing colorscheme joker

### ISSUE THREAD

**Issue by TrevCan** [arthurealike/vim-J#3]
When I execute `:colorscheme joker` from vim, I get this error: `Error detected while processing C:\Users\{userName}\Vim\vim-plug\vim-J\colors\joker.vim:                                     line   82:                                                                                                              E421: Color name or number not recognized: ctermbg=jblack ctermfg=white cterm=NONE`.

Likewise, when I write it in my [_vimrc](https://gist.github.com/TrevCan/4b2dc3e5c97e691258acaa265642042c) it returns an error but it disappears very fast. After pressing enter, vim works but the colorscheme isn't set.

**Comment by TrevCan** [comment]
**Apparently**, if I run `:set termguicolors` before executing `:colorscheme joker` it works. Is this how it should work? I've tested this on Windows Terminal using powershell 7.

**Comment by arthurealike** [comment]
Yes, you need to put `set termguicolors` on your _vimrc.

**Comment by TrevCan** [comment]
Thanks, I'd recommend adding it before executing the `colorscheme joker` in the readme, it seems as if it were optional.
